CREATE TABLE IF NOT EXISTS target_health_buckets (
    bucket_start INTEGER NOT NULL,
    scope TEXT NOT NULL CHECK (scope IN ('provider', 'account', 'model')),
    provider_id TEXT NOT NULL,
    account_id TEXT NOT NULL DEFAULT '',
    model_id TEXT NOT NULL DEFAULT '',
    attempts INTEGER NOT NULL DEFAULT 0,
    successes INTEGER NOT NULL DEFAULT 0,
    fallback_failures INTEGER NOT NULL DEFAULT 0,
    rate_limits INTEGER NOT NULL DEFAULT 0,
    quota_exhausted INTEGER NOT NULL DEFAULT 0,
    server_5xx INTEGER NOT NULL DEFAULT 0,
    connection_errors INTEGER NOT NULL DEFAULT 0,
    timeouts INTEGER NOT NULL DEFAULT 0,
    cancellations INTEGER NOT NULL DEFAULT 0,
    fallbacks INTEGER NOT NULL DEFAULT 0,
    adaptive_saturation INTEGER NOT NULL DEFAULT 0,
    provider_circuit_rejects INTEGER NOT NULL DEFAULT 0,
    provider_circuit_opens INTEGER NOT NULL DEFAULT 0,
    provider_circuit_recoveries INTEGER NOT NULL DEFAULT 0,
    half_open_probes INTEGER NOT NULL DEFAULT 0,
    ttft_b0 INTEGER NOT NULL DEFAULT 0,
    ttft_b1 INTEGER NOT NULL DEFAULT 0,
    ttft_b2 INTEGER NOT NULL DEFAULT 0,
    ttft_b3 INTEGER NOT NULL DEFAULT 0,
    ttft_b4 INTEGER NOT NULL DEFAULT 0,
    ttft_b5 INTEGER NOT NULL DEFAULT 0,
    ttft_b6 INTEGER NOT NULL DEFAULT 0,
    ttft_b7 INTEGER NOT NULL DEFAULT 0,
    ttft_b8 INTEGER NOT NULL DEFAULT 0,
    ttft_b9 INTEGER NOT NULL DEFAULT 0,
    duration_b0 INTEGER NOT NULL DEFAULT 0,
    duration_b1 INTEGER NOT NULL DEFAULT 0,
    duration_b2 INTEGER NOT NULL DEFAULT 0,
    duration_b3 INTEGER NOT NULL DEFAULT 0,
    duration_b4 INTEGER NOT NULL DEFAULT 0,
    duration_b5 INTEGER NOT NULL DEFAULT 0,
    duration_b6 INTEGER NOT NULL DEFAULT 0,
    duration_b7 INTEGER NOT NULL DEFAULT 0,
    duration_b8 INTEGER NOT NULL DEFAULT 0,
    duration_b9 INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (bucket_start, scope, provider_id, account_id, model_id)
);

CREATE INDEX IF NOT EXISTS idx_target_health_buckets_window
    ON target_health_buckets(bucket_start);
