//! Wasmtime host runtime for plugins (§4, §7, §14, §15).
//!
//! One [`PluginRuntime`] owns a Wasmtime [`Engine`] configured with epoch-based
//! interruption (so a runaway guest cannot block the host) and a memory cap. A
//! per-plugin instance pool keeps instantiation off the request path.
//!
//! The WIT world is generated by `bindgen!` from `wit/kinetix-plugin.wit`. Host
//! imports are wired to [`HostCtx`], which enforces the plugin's granted
//! permissions: network host allow-list, storage namespace, and logging.

use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::Duration;

use anyhow::Result;
use wasmtime::component::{Component, Linker};
use wasmtime::{Config, Engine, Store, StoreLimits, StoreLimitsBuilder};

pub mod bindings {
    wasmtime::component::bindgen!({
        path: "wit/kinetix-plugin.wit",
        world: "plugin",
        imports: { default: async | trappable },
        exports: { default: async },
        anyhow: true,
    });
}

/// Optional account-authorization world. Separate binding preserves API-v1
/// compatibility for components that do not provide browser auth.
pub mod auth_bindings {
    wasmtime::component::bindgen!({
        path: "wit/kinetix-plugin.wit",
        world: "plugin-auth",
        imports: { default: async | trappable },
        exports: { default: async },
        anyhow: true,
    });
}

/// Adapter world (§6.3, §7.1). Kept separate so the buffered host-http import
/// can never be used as the adapter transport. Adapters are synchronous
/// translation functions, so this world is bound synchronously and invoked via
/// `block_in_place` (see `PluginAdapter`).
pub mod adapter_bindings {
    wasmtime::component::bindgen!({
        path: "wit/kinetix-plugin.wit",
        world: "plugin-adapter",
        imports: { default: async | trappable },
        exports: { default: async },
        anyhow: true,
    });
}

pub use bindings::kinetix::plugin as wit;

/// Reserved KV namespace for cached routing facts (§6.4). Values written here
/// are host-stamped with `observed_at`/`max_age_ms`.
pub const CACHE_PREFIX: &str = "_cache:";
/// Reserved host-owned plugin configuration namespace. Guests may read values
/// through host-storage but may not write or delete them.
pub const CONFIG_PREFIX: &str = "_config:";

/// Errors that terminate or fail a plugin invocation.
#[derive(Debug, Clone)]
pub enum PluginFault {
    /// The guest trapped (panic, unreachable, stack overflow, ...).
    Trap(String),
    /// The invocation exceeded its wall-time budget and was epoch-interrupted.
    Timeout,
    /// A host-capability call was forbidden by the plugin's permissions.
    PermissionDenied(String),
    /// The guest returned an ill-typed or out-of-contract value.
    InvalidResult(String),
    /// The plugin reported a structured error.
    PluginError {
        code: String,
        message: String,
        retryable: bool,
    },
    /// The client disconnected and the invocation was terminated (§7.2). This
    /// is deliberately not a fault and never counts against the circuit.
    Cancelled,
    /// Anything else (host-side failure).
    Internal(String),
}

impl PluginFault {
    /// The §17 failure code for this fault.
    pub fn code(&self) -> &str {
        match self {
            PluginFault::Trap(_) => "plugin_internal",
            PluginFault::Timeout => "timeout",
            PluginFault::PermissionDenied(_) => "permission_denied",
            PluginFault::InvalidResult(_) => "protocol_error",
            PluginFault::PluginError { code, .. } => code,
            PluginFault::Cancelled => "cancelled",
            PluginFault::Internal(_) => "plugin_internal",
        }
    }

    /// Whether this fault should count against the plugin's circuit breaker
    /// (§15). Structured plugin errors (e.g. upstream 429 classification) do
    /// not; runtime faults do.
    pub fn counts_against_circuit(&self) -> bool {
        matches!(
            self,
            PluginFault::Trap(_)
                | PluginFault::Timeout
                | PluginFault::PermissionDenied(_)
                | PluginFault::InvalidResult(_)
                | PluginFault::Internal(_)
        )
    }

    pub fn message(&self) -> String {
        match self {
            PluginFault::Trap(m) => format!("guest trapped: {m}"),
            PluginFault::Timeout => "plugin invocation timed out".into(),
            PluginFault::PermissionDenied(m) => format!("permission denied: {m}"),
            PluginFault::InvalidResult(m) => format!("invalid result: {m}"),
            PluginFault::PluginError { code, message, .. } => format!("{code}: {message}"),
            PluginFault::Cancelled => "invocation cancelled by client".into(),
            PluginFault::Internal(m) => m.clone(),
        }
    }
}

impl std::fmt::Display for PluginFault {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.message())
    }
}

/// Per-store host context. Every host-import closure receives this.
pub struct HostCtx {
    /// The plugin id this store belongs to (namespaces storage and logs).
    pub plugin_id: String,
    /// Granted network hosts (already validated, §9).
    pub network_hosts: Vec<String>,
    /// Operator-owned development override for private/internal destinations.
    /// This is never derived from plugin manifest data.
    pub allow_private_network: bool,
    /// Whether the plugin may read plaintext credentials (§8.2).
    pub credential_read: bool,
    /// Whether the plugin may use host-side credential signing (§7.3).
    pub credential_sign: bool,
    /// Granted credential scopes (`provider:<id>`).
    pub credential_scopes: Vec<String>,
    /// Storage quota in bytes.
    pub storage_quota: u64,
    /// Max outbound requests per invocation.
    pub max_outbound_requests: u32,
    /// Max outbound body size.
    pub max_http_body: u64,
    /// Whether the plugin may open the streaming adapter transport (§7.1).
    pub adapter_stream: bool,
    /// Whether this specific invocation may use buffered host-http. Authority
    /// is capability-scoped by the manager: routing-fact request-path calls and
    /// provider-adapter calls set this to false even when the plugin has approved
    /// network hosts.
    pub buffered_http_allowed: bool,
    /// Outbound request counter for the current invocation.
    pub outbound_count: u32,
    /// Storage + credential side effects are deferred to async host functions;
    /// this holds the backing handles.
    pub backing: Arc<dyn HostBacking>,
    // §4 WASI policy: no ambient WASI authority is granted. The plugin world
    // imports no WASI interfaces and no resources, so no WASI context or
    // resource table is provided; a component that imports WASI is refused at
    // instantiation.
    pub limits: StoreLimits,
}

/// Host-side effects a plugin may trigger. Implemented by the manager so the
/// runtime stays decoupled from the database.
#[async_trait::async_trait]
pub trait HostBacking: Send + Sync {
    /// Read a plugin KV value (already decrypted by the backing).
    async fn kv_get(&self, plugin_id: &str, key: &str) -> Result<Option<Vec<u8>>>;
    async fn kv_put(&self, plugin_id: &str, key: &str, value: &[u8]) -> Result<()>;
    async fn kv_delete(&self, plugin_id: &str, key: &str) -> Result<()>;
    /// Check whether one of the approved credential scopes authorizes this
    /// plugin to use credentials belonging to the target provider.
    async fn credential_scope_allows(
        &self,
        plugin_id: &str,
        provider_id: &str,
        scopes: &[String],
    ) -> Result<bool>;
    /// Emit a namespaced, redacted log line (§18).
    fn log(&self, plugin_id: &str, level: &str, message: &str);
    /// Resolve the plaintext secret for a credential ref (§8.1/§8.2). Only
    /// reachable when `credential_read` is granted.
    async fn resolve_secret(
        &self,
        plugin_id: &str,
        provider_id: &str,
        account_id: &str,
    ) -> Result<String>;
}

/// A configured Wasmtime host runtime shared by every plugin instance.
#[derive(Clone)]
pub struct PluginRuntime {
    engine: Engine,
}

impl PluginRuntime {
    /// Build an engine with epoch interruption, a memory cap, and the
    /// component-model features the plugin API requires.
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        config.wasm_component_model_async(true);
        config.epoch_interruption(true);
        config.consume_fuel(false);
        // Bound the guest's linear memory; per-store limits also apply.
        config.max_wasm_stack(1024 * 1024);
        let engine =
            Engine::new(&config).map_err(|e| anyhow::anyhow!("building wasmtime engine: {e}"))?;
        Ok(PluginRuntime { engine })
    }

    pub fn engine(&self) -> &Engine {
        &self.engine
    }

    /// Compile a component. Compilation is itself bounded: it happens at
    /// install/enable time, never on the request path.
    pub fn compile(&self, wasm: &[u8]) -> Result<Component> {
        Component::new(&self.engine, wasm)
            .map_err(|e| anyhow::anyhow!("compiling plugin component: {e}"))
    }

    /// Build a store for one plugin invocation.
    pub fn new_store(&self, mut ctx: HostCtx, memory_limit: u64) -> Store<HostCtx> {
        let limits = StoreLimitsBuilder::new()
            .memory_size(memory_limit as usize)
            .trap_on_grow_failure(true)
            .build();
        ctx.limits = limits;
        let mut store = Store::new(&self.engine, ctx);
        store.limiter(|c| &mut c.limits);
        // Default epoch deadline; callers override per capability (§14).
        store.set_epoch_deadline(1);
        store
    }

    /// Build a linker with every host import wired to permission checks.
    pub fn linker(&self) -> Result<Linker<HostCtx>> {
        let mut linker: Linker<HostCtx> = Linker::new(&self.engine);
        bindings::Plugin::add_to_linker::<_, wasmtime::component::HasSelf<HostCtx>>(
            &mut linker,
            |ctx| ctx,
        )
        .map_err(|e| anyhow::anyhow!("wiring plugin host imports: {e}"))?;
        Ok(linker)
    }

    /// Instantiate a component against a prepared linker/store.
    pub async fn instantiate(
        &self,
        linker: &Linker<HostCtx>,
        store: &mut Store<HostCtx>,
        component: &Component,
    ) -> Result<bindings::Plugin> {
        bindings::Plugin::instantiate_async(store, component, linker)
            .await
            .map_err(|e| anyhow::anyhow!("instantiating plugin component: {e}"))
    }

    /// Instantiate the optional browser/account authorization world.
    pub async fn instantiate_auth(
        &self,
        linker: &Linker<HostCtx>,
        store: &mut Store<HostCtx>,
        component: &Component,
    ) -> Result<auth_bindings::PluginAuth> {
        auth_bindings::PluginAuth::instantiate_async(store, component, linker)
            .await
            .map_err(|e| anyhow::anyhow!("instantiating plugin auth component: {e}"))
    }

    /// Instantiate the adapter world (§6.3). Uses the same linker (the host
    /// imports are identical) but the `plugin-adapter` exports.
    pub async fn instantiate_adapter(
        &self,
        linker: &Linker<HostCtx>,
        store: &mut Store<HostCtx>,
        component: &Component,
    ) -> Result<adapter_bindings::PluginAdapter> {
        adapter_bindings::PluginAdapter::instantiate_async(store, component, linker)
            .await
            .map_err(|e| anyhow::anyhow!("instantiating plugin adapter component: {e}"))
    }

    /// Arm a wall-time budget for a store (§14, §15): the returned guard bumps
    /// the engine epoch every 10 ms; when the guest's deadline is reached the
    /// epoch interruption traps it (surfaced as [`PluginFault::Timeout`]).
    ///
    /// Dropping the guard cancels the ticker, so it must be held for the whole
    /// duration of the guest call.
    pub fn arm_deadline(&self, store: &mut Store<HostCtx>, wall_time: Duration) -> DeadlineGuard {
        let ticks = (wall_time.as_millis().max(1) as u64).div_ceil(10).max(1);
        store.set_epoch_deadline(ticks);
        let engine = self.engine.clone();
        let handle = tokio::spawn(async move {
            let mut elapsed = 0u64;
            while elapsed < ticks {
                tokio::time::sleep(Duration::from_millis(10)).await;
                elapsed += 1;
                engine.increment_epoch();
            }
        });
        DeadlineGuard {
            handle,
            cancelled: std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false)),
        }
    }
}

/// Cancels the epoch ticker when dropped.
pub struct DeadlineGuard {
    handle: tokio::task::JoinHandle<()>,
    /// Set when the invocation was cancelled by the client rather than by its
    /// own budget, so a cancellation is not counted as a plugin fault (§7.2).
    pub cancelled: std::sync::Arc<std::sync::atomic::AtomicBool>,
}

impl DeadlineGuard {
    /// Mark the invocation as client-cancelled. The next epoch interrupt aborts
    /// the guest, and the resulting trap is classified as a cancellation.
    pub fn cancel(&self) {
        self.cancelled
            .store(true, std::sync::atomic::Ordering::SeqCst);
    }
    /// Whether the invocation was client-cancelled.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(std::sync::atomic::Ordering::SeqCst)
    }
}

impl Drop for DeadlineGuard {
    fn drop(&mut self) {
        self.handle.abort();
    }
}

impl Default for PluginRuntime {
    fn default() -> Self {
        Self::new().expect("default plugin runtime")
    }
}

// ---------------------------------------------------------------------------
// Host import implementations (§7, §8, §9, §10)
// ---------------------------------------------------------------------------

fn err(code: &str, message: impl Into<String>) -> wit::types::PluginError {
    wit::types::PluginError {
        code: code.to_string(),
        message: message.into(),
        retryable: false,
        retry_after: None,
        reset_at: None,
    }
}

impl bindings::kinetix::plugin::types::Host for HostCtx {}

fn blocked_plugin_hostname(host: &str) -> bool {
    let lower = host.to_ascii_lowercase();
    lower == "localhost"
        || lower.ends_with(".localhost")
        || lower.ends_with(".internal")
        || lower == "metadata.google.internal"
}

async fn resolve_plugin_destination(
    host: &str,
    port: u16,
    allow_private_network: bool,
) -> Result<Vec<SocketAddr>, String> {
    if !allow_private_network && blocked_plugin_hostname(host) {
        return Err(format!("host '{host}' is a blocked private/metadata destination"));
    }

    if let Ok(ip) = host.parse::<IpAddr>() {
        if !allow_private_network && crate::admin::is_blocked_ip(ip) {
            return Err(format!("host '{host}' is a blocked private/metadata address"));
        }
        return Ok(vec![SocketAddr::new(ip, port)]);
    }

    let resolved = tokio::net::lookup_host((host, port))
        .await
        .map_err(|e| format!("DNS resolution for '{host}' failed: {e}"))?;
    let mut addrs = Vec::new();
    for addr in resolved {
        if !allow_private_network && crate::admin::is_blocked_ip(addr.ip()) {
            return Err(format!(
                "host '{host}' resolves to a blocked private/metadata address ({})",
                addr.ip()
            ));
        }
        if !addrs.contains(&addr) {
            addrs.push(addr);
        }
    }
    if addrs.is_empty() {
        return Err(format!("DNS resolution for '{host}' returned no addresses"));
    }
    Ok(addrs)
}

fn pinned_plugin_client(host: &str, addrs: &[SocketAddr]) -> Result<reqwest::Client, String> {
    reqwest::Client::builder()
        .https_only(true)
        .connect_timeout(Duration::from_secs(10))
        .redirect(reqwest::redirect::Policy::none())
        .http2_adaptive_window(true)
        .user_agent(concat!("kinetix-plugin-host/", env!("CARGO_PKG_VERSION")))
        .resolve_to_addrs(host, addrs)
        .build()
        .map_err(|e| format!("building pinned outbound client failed: {e}"))
}

impl bindings::kinetix::plugin::host_http::Host for HostCtx {
    async fn send(
        &mut self,
        req: wit::types::HttpRequest,
    ) -> anyhow::Result<Result<wit::types::HttpResponse, wit::types::PluginError>> {
        // Buffered host-http is control-plane only. Authority is scoped per
        // invocation by the manager, so request-path routing facts and
        // adapter-world calls are denied even when approved network hosts exist.
        if !self.buffered_http_allowed {
            return Ok(Err(err(
                "permission_denied",
                "buffered host-http is not available to this plugin capability",
            )));
        }
        if self.outbound_count >= self.max_outbound_requests {
            return Ok(Err(err(
                "permission_denied",
                "outbound request budget exhausted",
            )));
        }
        let parsed = match url::Url::parse(&req.url) {
            Ok(u) => u,
            Err(_) => return Ok(Err(err("invalid_configuration", "invalid URL"))),
        };
        if parsed.scheme() != "https" {
            return Ok(Err(err(
                "permission_denied",
                "only https outbound requests are permitted",
            )));
        }
        if !parsed.username().is_empty() || parsed.password().is_some() {
            return Ok(Err(err(
                "invalid_configuration",
                "outbound URLs may not contain userinfo",
            )));
        }
        let Some(host) = parsed.host_str().map(|h| h.to_ascii_lowercase()) else {
            return Ok(Err(err("invalid_configuration", "URL has no host")));
        };
        // §9: manifest hostname check with conservative wildcard matching.
        let allowed = self
            .network_hosts
            .iter()
            .any(|p| super::manifest::host_matches(p, &host));
        if !allowed {
            return Ok(Err(err(
                "permission_denied",
                format!("host '{host}' is not in the plugin's network_hosts"),
            )));
        }
        if req.body.len() as u64 > self.max_http_body {
            return Ok(Err(err("permission_denied", "request body too large")));
        }

        // Resolve once, reject every blocked answer, and pin those exact
        // addresses into reqwest so a second DNS lookup cannot rebind the
        // request to loopback/private/link-local/metadata space.
        let port = parsed.port_or_known_default().unwrap_or(443);
        let addrs = match resolve_plugin_destination(
            &host,
            port,
            self.allow_private_network,
        )
        .await
        {
            Ok(addrs) => addrs,
            Err(message) => return Ok(Err(err("permission_denied", message))),
        };
        let client = match pinned_plugin_client(&host, &addrs) {
            Ok(client) => client,
            Err(message) => return Ok(Err(err("upstream_unavailable", message))),
        };

        // Credential injection is a host responsibility (§8.1). The plugin only
        // references a credential; it never sees the bytes.
        let mut builder = match req.method.to_ascii_uppercase().as_str() {
            "GET" => client.get(parsed.clone()),
            "POST" => client.post(parsed.clone()),
            "PUT" => client.put(parsed.clone()),
            "DELETE" => client.delete(parsed.clone()),
            "PATCH" => client.patch(parsed.clone()),
            _ => return Ok(Err(err("invalid_configuration", "unsupported method"))),
        };
        for (k, v) in &req.headers {
            builder = builder.header(k, v);
        }
        if let Some(cred) = &req.credential {
            match self.inject_credential(cred).await {
                Ok(Some((name, value))) => builder = builder.header(name, value),
                Ok(None) => {}
                Err(e) => return Ok(Err(err("permission_denied", e))),
            }
        }
        if !req.body.is_empty() {
            builder = builder.body(req.body.clone());
        }

        self.outbound_count += 1;
        let resp = match builder.send().await {
            Ok(r) => r,
            Err(e) => {
                return Ok(Err(wit::types::PluginError {
                    code: "upstream_unavailable".into(),
                    message: format!("outbound request failed: {}", classify_reqwest(&e)),
                    retryable: true,
                    retry_after: None,
                    reset_at: None,
                }))
            }
        };
        let status = resp.status().as_u16();
        let headers: Vec<(String, String)> = resp
            .headers()
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
            .collect();
        // Bound the buffered response; a truncated body is reported honestly
        // rather than silently accepted as complete (§9, §14).
        let (body, body_truncated) = read_bounded(resp, self.max_http_body).await;
        Ok(Ok(wit::types::HttpResponse {
            status,
            headers,
            body,
            body_truncated,
        }))
    }
}

/// Read a response body up to `limit` bytes; the second value is true when the
/// body was cut off.
async fn read_bounded(mut resp: reqwest::Response, limit: u64) -> (Vec<u8>, bool) {
    let mut out: Vec<u8> = Vec::new();
    while let Ok(Some(chunk)) = resp.chunk().await {
        if out.len() as u64 + chunk.len() as u64 > limit {
            let take = limit.saturating_sub(out.len() as u64) as usize;
            out.extend_from_slice(&chunk[..take.min(chunk.len())]);
            return (out, true);
        }
        out.extend_from_slice(&chunk);
    }
    (out, false)
}

impl HostCtx {
    /// Resolve a credential ref into a `(header_name, value)` to inject, or an
    /// error string when the plugin is not authorized.
    async fn inject_credential(
        &self,
        cred: &wit::types::CredentialRef,
    ) -> Result<Option<(String, String)>, String> {
        let (provider_id, account_id) = match cred {
            wit::types::CredentialRef::Account(a) => (a.provider_id.clone(), a.account_id.clone()),
            wit::types::CredentialRef::Named(_) => {
                return Err("named credentials are not resolvable in v1".into())
            }
        };
        if !self
            .scope_allows(&provider_id)
            .await
            .map_err(|e| format!("credential scope check failed: {e}"))?
        {
            return Err(format!("plugin is not scoped to provider '{provider_id}'"));
        }
        let secret = self
            .backing
            .resolve_secret(&self.plugin_id, &provider_id, &account_id)
            .await
            .map_err(|e| format!("credential resolution failed: {e}"))?;
        Ok(Some((
            "authorization".to_string(),
            format!("Bearer {secret}"),
        )))
    }

    async fn scope_allows(&self, provider_id: &str) -> Result<bool> {
        self.backing
            .credential_scope_allows(&self.plugin_id, provider_id, &self.credential_scopes)
            .await
    }
}

impl bindings::kinetix::plugin::host_storage::Host for HostCtx {
    async fn get(&mut self, key: String) -> anyhow::Result<Option<Vec<u8>>> {
        Ok(self
            .backing
            .kv_get(&self.plugin_id, &key)
            .await
            .ok()
            .flatten())
    }

    async fn put(&mut self, key: String, value: Vec<u8>) -> anyhow::Result<Result<(), String>> {
        if key.starts_with(CONFIG_PREFIX) {
            return Ok(Err("host-owned config namespace is read-only".into()));
        }
        let used = self
            .backing
            .kv_get(&self.plugin_id, "")
            .await
            .ok()
            .flatten()
            .map(|v| v.len() as u64)
            .unwrap_or(0);
        if used + value.len() as u64 > self.storage_quota {
            return Ok(Err("storage quota exceeded".into()));
        }
        match self.backing.kv_put(&self.plugin_id, &key, &value).await {
            Ok(()) => Ok(Ok(())),
            Err(e) => Ok(Err(format!("storage write failed: {e}"))),
        }
    }

    async fn delete(&mut self, key: String) -> anyhow::Result<Result<(), String>> {
        if key.starts_with(CONFIG_PREFIX) {
            return Ok(Err("host-owned config namespace is read-only".into()));
        }
        match self.backing.kv_delete(&self.plugin_id, &key).await {
            Ok(()) => Ok(Ok(())),
            Err(e) => Ok(Err(format!("storage delete failed: {e}"))),
        }
    }

    async fn cache_set(
        &mut self,
        name: String,
        value_json: String,
        max_age_ms: u64,
    ) -> anyhow::Result<Result<(), String>> {
        // §6.4: cached routing facts are host-stamped so a `cached` provider
        // cannot make Routes non-deterministic by lying about `observed_at`.
        if serde_json::from_str::<serde_json::Value>(&value_json).is_err() {
            return Ok(Err("cache value is not valid JSON".into()));
        }
        if max_age_ms == 0 || max_age_ms > 24 * 3600 * 1000 {
            return Ok(Err("max_age_ms out of range".into()));
        }
        let envelope = serde_json::json!({
            "value": serde_json::from_str::<serde_json::Value>(&value_json)
                .unwrap_or(serde_json::Value::Null),
            "observed_at": crate::db::now_iso(),
            "max_age_ms": max_age_ms,
        })
        .to_string();
        let key = format!("{CACHE_PREFIX}{name}");
        match self
            .backing
            .kv_put(&self.plugin_id, &key, envelope.as_bytes())
            .await
        {
            Ok(()) => Ok(Ok(())),
            Err(e) => Ok(Err(format!("cache write failed: {e}"))),
        }
    }
}

impl bindings::kinetix::plugin::host_log::Host for HostCtx {
    async fn log(&mut self, level: wit::host_log::Level, message: String) -> anyhow::Result<()> {
        let level = match level {
            wit::host_log::Level::Trace => "trace",
            wit::host_log::Level::Debug => "debug",
            wit::host_log::Level::Info => "info",
            wit::host_log::Level::Warn => "warn",
            wit::host_log::Level::Error => "error",
        };
        // §18: plugin logs are namespaced and redacted exactly like core logs.
        let redacted = crate::crypto::redact(&message);
        self.backing.log(&self.plugin_id, level, &redacted);
        Ok(())
    }
}

impl bindings::kinetix::plugin::host_clock::Host for HostCtx {
    async fn now_unix_seconds(&mut self) -> anyhow::Result<u64> {
        Ok(std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0))
    }
    async fn now_unix_millis(&mut self) -> anyhow::Result<u64> {
        Ok(std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0))
    }
}

impl bindings::kinetix::plugin::host_credential::Host for HostCtx {
    async fn sign(
        &mut self,
        mut req: wit::types::HttpRequest,
        credential: wit::types::CredentialRef,
    ) -> anyhow::Result<Result<wit::types::HttpRequest, wit::types::PluginError>> {
        if !self.credential_sign {
            return Ok(Err(err(
                "permission_denied",
                "plugin has no credential signing grant",
            )));
        }
        match self.inject_credential(&credential).await {
            Ok(Some((name, value))) => {
                req.headers.push((name, value));
                Ok(Ok(req))
            }
            Ok(None) => Ok(Ok(req)),
            Err(e) => Ok(Err(err("permission_denied", e))),
        }
    }

    async fn lease(
        &mut self,
        credential: wit::types::CredentialRef,
    ) -> anyhow::Result<Result<String, wit::types::PluginError>> {
        if !self.credential_sign && !self.credential_read {
            return Ok(Err(err(
                "permission_denied",
                "plugin has no credential lease grant",
            )));
        }
        let (provider_id, account_id) = match &credential {
            wit::types::CredentialRef::Account(a) => (a.provider_id.clone(), a.account_id.clone()),
            wit::types::CredentialRef::Named(_) => {
                return Ok(Err(err("invalid_configuration", "named credential")));
            }
        };
        let scoped = self.scope_allows(&provider_id).await.unwrap_or(false);
        if !scoped {
            return Ok(Err(err(
                "permission_denied",
                format!("plugin is not scoped to provider '{provider_id}'"),
            )));
        }
        // Opaque handle: derived, non-reversible, and never the secret (§6.1).
        let handle = format!(
            "lease_{}",
            hex::encode(sha2::Sha256::digest(
                format!("{}:{}:{}", self.plugin_id, provider_id, account_id).as_bytes()
            ))
        );
        Ok(Ok(handle))
    }

    async fn read(
        &mut self,
        credential: wit::types::CredentialRef,
    ) -> anyhow::Result<Result<String, wit::types::PluginError>> {
        // §8.2: plaintext credential read is a distinct, higher-risk grant and
        // is only reachable when the manifest declares `credential_read`.
        if !self.credential_read {
            return Ok(Err(err(
                "permission_denied",
                "plugin has no credential_read grant",
            )));
        }
        match self.inject_credential(&credential).await {
            // `inject_credential` returns a pre-formatted `Bearer` header; strip
            // the scheme so the guest receives just the secret it asked for.
            Ok(Some((_, value))) => {
                let secret = value.strip_prefix("Bearer ").unwrap_or(&value).to_string();
                Ok(Ok(secret))
            }
            Ok(None) => Ok(Err(err("unknown", "credential not resolvable"))),
            Err(e) => Ok(Err(err("permission_denied", e))),
        }
    }
}

fn classify_reqwest(e: &reqwest::Error) -> String {
    if e.is_timeout() {
        "timeout".into()
    } else if e.is_connect() {
        "connection error".into()
    } else {
        "request error".into()
    }
}

use sha2::Digest;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_builds_with_component_and_epoch() {
        let rt = PluginRuntime::new().unwrap();
        let linker = rt.linker().unwrap();
        drop(linker);
    }

    #[test]
    fn enforces_the_plugin_world_exports() {
        // A well-formed component that does not implement the plugin world must
        // be refused at instantiation: this is what keeps `plugin_api` honest
        // and rejects a package that claims the wrong interface (AC#4).
        let rt = PluginRuntime::new().unwrap();
        let empty = rt
            .compile(b"(component)")
            .expect("an empty component should compile");
        let linker = rt.linker().unwrap();
        let ctx = HostCtx {
            plugin_id: "test".into(),
            network_hosts: vec![],
            allow_private_network: false,
            credential_read: false,
            credential_sign: false,
            credential_scopes: vec![],
            storage_quota: 1024,
            max_outbound_requests: 1,
            max_http_body: 1024,
            adapter_stream: false,
            buffered_http_allowed: false,
            outbound_count: 0,
            backing: std::sync::Arc::new(NoBacking),
            limits: wasmtime::StoreLimitsBuilder::new().build(),
        };
        let mut store = rt.new_store(ctx, 1024 * 1024);
        let result = futures::executor::block_on(rt.instantiate(&linker, &mut store, &empty));
        assert!(
            result.is_err(),
            "an empty component must not satisfy the world"
        );
    }

    fn test_ctx(buffered_http_allowed: bool, network_hosts: Vec<String>) -> HostCtx {
        HostCtx {
            plugin_id: "test".into(),
            network_hosts,
            allow_private_network: false,
            credential_read: false,
            credential_sign: false,
            credential_scopes: vec![],
            storage_quota: 1024,
            max_outbound_requests: 1,
            max_http_body: 1024,
            adapter_stream: false,
            buffered_http_allowed,
            outbound_count: 0,
            backing: std::sync::Arc::new(NoBacking),
            limits: wasmtime::StoreLimitsBuilder::new().build(),
        }
    }

    #[tokio::test]
    async fn plugin_destination_rejects_private_ip_literals_by_default() {
        for host in ["127.0.0.1", "10.1.2.3", "169.254.169.254", "::1", "fc00::1", "fe80::1"] {
            let err = resolve_plugin_destination(host, 443, false)
                .await
                .unwrap_err();
            assert!(err.contains("blocked"), "{host}: {err}");
        }
    }

    #[tokio::test]
    async fn plugin_destination_private_override_is_operator_controlled() {
        let addrs = resolve_plugin_destination("127.0.0.1", 8443, true)
            .await
            .unwrap();
        assert_eq!(addrs, vec!["127.0.0.1:8443".parse().unwrap()]);
    }

    #[test]
    fn plugin_destination_blocks_internal_hostnames_before_dns() {
        for host in ["localhost", "api.localhost", "metadata.google.internal", "db.internal"] {
            assert!(blocked_plugin_hostname(host), "{host}");
        }
        assert!(!blocked_plugin_hostname("api.example.com"));
    }

    #[tokio::test]
    async fn buffered_http_is_scoped_to_the_current_capability() {
        use bindings::kinetix::plugin::host_http::Host;

        let req = wit::types::HttpRequest {
            method: "GET".into(),
            url: "https://oauth2.googleapis.com/token".into(),
            headers: vec![],
            body: vec![],
            credential: None,
        };

        let mut denied = test_ctx(false, vec!["oauth2.googleapis.com".into()]);
        let err = denied.send(req.clone()).await.unwrap().unwrap_err();
        assert_eq!(err.code, "permission_denied");
        assert!(err
            .message
            .contains("not available to this plugin capability"));

        // With capability-level HTTP enabled, the request advances to the
        // manifest host allow-list instead of being rejected by capability policy.
        let mut allowed_capability = test_ctx(true, vec!["api.example.com".into()]);
        let err = allowed_capability.send(req).await.unwrap().unwrap_err();
        assert_eq!(err.code, "permission_denied");
        assert!(err.message.contains("network_hosts"));
    }

    struct NoBacking;
    #[async_trait::async_trait]
    impl HostBacking for NoBacking {
        async fn kv_get(&self, _: &str, _: &str) -> anyhow::Result<Option<Vec<u8>>> {
            Ok(None)
        }
        async fn kv_put(&self, _: &str, _: &str, _: &[u8]) -> anyhow::Result<()> {
            Ok(())
        }
        async fn kv_delete(&self, _: &str, _: &str) -> anyhow::Result<()> {
            Ok(())
        }
        async fn credential_scope_allows(
            &self,
            _: &str,
            _: &str,
            _: &[String],
        ) -> anyhow::Result<bool> {
            Ok(false)
        }
        fn log(&self, _: &str, _: &str, _: &str) {}
        async fn resolve_secret(&self, _: &str, _: &str, _: &str) -> anyhow::Result<String> {
            Ok(String::new())
        }
    }

    #[test]
    fn fault_classification_matches_section_17() {
        assert_eq!(PluginFault::Timeout.code(), "timeout");
        assert!(PluginFault::Timeout.counts_against_circuit());
        // A structured upstream failure is evidence, not a runtime fault.
        let e = PluginFault::PluginError {
            code: "rate_limited".into(),
            message: "429".into(),
            retryable: true,
        };
        assert!(!e.counts_against_circuit());
        assert_eq!(e.code(), "rate_limited");
    }
}
